### ISSUE TITLE
Issue - Installation

### ISSUE THREAD

**Issue by atsamaei** [conda-forge/luarocks-feedstock#18]
Issue:
Hello,
 
When I try to install luarocks based on your instruction, I am getting the following error. I am using Anaconda. Would you please let me know how to resolve the issue? Thank you.

 (Por) C:\Users\ara>    conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top

(Por) C:\Users\ara>     conda install luarocks
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - luarocks

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by izahn** [comment]
`luarocks` is not available form conda-forge on windows, as seen in https://github.com/conda-forge/luarocks-feedstock/blob/f95e009a94294a9f1be01b0e3de6d056ca302794/recipe/meta.yaml#L16

**Comment by anjos** [comment]
Closing this issue based on the comment above.
